server:
  port: 8888
spring:
  datasource:
    url: jdbc:sqlite:dblist.db
    driver-class-name: org.sqlite.JDBC
    username: springuser
    password: ThePassword
  jpa:
    database-platform: com.myohanhtet.dirctonary.config.SQLiteDialect